version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15

commands:
  checkout-and-dependencies:
    description: "Checkout and install dependencies, managing a cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # With --frozen-lockfile, the installation will fail if the lockfile is
      # outdated compared to package.json.
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  master:
    jobs:
      - tests
      - lint
      - build
      - flow
      - docker

jobs:
  lint:
    executor: node
    steps:
      - checkout-and-dependencies
      - run: yarn lint

  tests:
    executor: node
    steps:
      - checkout-and-dependencies
      - run: yarn test --runInBand

  flow:
    executor: node
    steps:
      - checkout-and-dependencies
      - run: yarn flow:ci

  build:
    executor: node
    steps:
      - checkout-and-dependencies
      - run: |
          yarn build:clean
          yarn build

  docker:
    executor: node
    steps:
      # This job doesn't need the cached node_modules because they'll be
      # redownloaded when building the docker image.
      - checkout
      # This sets up a remote environment that's necessary to run docker commands.
      - setup_remote_docker
      - run:
          name: "Build the Docker image"
          command: yarn docker:build --pull --build-arg circle_build_url=$CIRCLE_BUILD_URL
      - run:
          name: "Start the docker image in a container and check it's running"
          command: |
            yarn docker:run:detached
            # Wait up to 10 seconds that the server is launched.
            timeout 10s sh \<<'EOF'
            while ! docker exec profiler-server curl --silent --show-error --fail http://localhost:8000/__version__ ; do
              sleep 1
            done
            EOF
            yarn docker:stop
